/* ═══════════════════════════════════════════════════════════════
   tests/tokenizer-parity.test.mjs — TP-1…TP-9

   The JS encoder (`ai/engine/bpe.mjs`) must return *exactly* the ids the
   Python tokenizer returns for the same text. A "close enough" port is how
   a browser-side chat quietly produces worse Hindi than the evaluation
   suite measured, so the comparison here is byte-for-byte on a fixture
   generated by `inference/encode_fixture.py`.

   The fixture is only trusted while it matches the artifact on disk: if
   `tokenizer.json` changes and the fixture is not regenerated, these tests
   fail rather than pass on stale ids.
   ═══════════════════════════════════════════════════════════════ */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { ByteLevelBPE, SPECIAL_TOKENS, loadTokenizer, toByteLevel, fromByteLevel,
  BYTE_LEVEL_PATTERN, bytesToUnicode } from '../ai/engine/bpe.mjs';

const BYTE_CHARS = bytesToUnicode();

const HERE = dirname(fileURLToPath(import.meta.url));
const ROOT = resolve(HERE, '..');
const FIXTURE = JSON.parse(readFileSync(resolve(HERE, 'fixtures/tokenizer_parity.json'), 'utf8'));
const ARTIFACT = resolve(ROOT, FIXTURE.artifact);
const SPEC = JSON.parse(readFileSync(resolve(ARTIFACT, 'tokenizer.json'), 'utf8'));
const META = JSON.parse(readFileSync(resolve(ARTIFACT, 'meta.json'), 'utf8'));
const bpe = new ByteLevelBPE(SPEC);

test('TP-1 the fixture was generated from the artifact in the repo', () => {
  const raw = readFileSync(resolve(ARTIFACT, 'tokenizer.json'));
  const sha = createHash('sha256').update(raw).digest('hex');
  assert.equal(sha, FIXTURE.artifact_sha256,
    'tests/fixtures/tokenizer_parity.json is stale — rerun ' +
    '`python inference/encode_fixture.py` against the current artifact');
  assert.equal(FIXTURE.tokenizer_version, META.tokenizer_version);
});

test('TP-2 the vocabulary is ours, complete, and small on purpose', () => {
  assert.equal(bpe.vocabSize, Object.keys(SPEC.model.vocab).length);
  assert.equal(bpe.vocabSize, FIXTURE.vocab_size);
  SPECIAL_TOKENS.forEach((token, index) => {
    assert.equal(bpe.vocab[token], index, `${token} must be added-token id ${index}`);
    assert.equal(bpe.specialIds.has(index), true);
  });
  // §7.2: 12–16k is the target, 32k the ceiling. This seed artifact is the
  // provisional 1k one used for the CPU smoke runs; a real Stage A run
  // retrains it (§7.2, open item in PROGRESS.md). Guard the ceiling here so
  // an accidental pretrained vocabulary (32k–50k) can never be adopted as
  // "ours" without failing a test.
  assert.ok(bpe.vocabSize <= 16384, `vocab ${bpe.vocabSize} is above the §7.2 target`);
  assert.equal(META.model_type.startsWith('byte-level BPE (our own'), true);
  // `meta.json` says byte_fallback true, the serialized model says false,
  // and both are honest about different things: coverage comes from the
  // 256-entry initial alphabet, not from the unused fallback flag (see the
  // note in ai/engine/bpe.mjs). The alphabet is what the loop below
  // actually checks, because it is what the encoder depends on.
  assert.equal(META.byte_fallback, true);
  assert.equal(SPEC.model.byte_fallback, false);
  // Every byte's character is present — that is what makes Devanagari and
  // emoji encodable at all.
  for (let b = 0; b < 256; b++) {
    assert.notEqual(bpe.vocab[BYTE_CHARS[b]], undefined, `byte ${b} is missing`);
  }
});

test('TP-3 the byte-level mapping is derived and round-trips every byte', () => {
  assert.equal(new Set(BYTE_CHARS).size, 256, 'the map must be injective');
  assert.equal(BYTE_CHARS[0x20], 'Ġ', 'a space is Ġ — the map is GPT-2 byte-level');
  for (let b = 0; b < 256; b++) {
    assert.equal(fromByteLevel(BYTE_CHARS[b])[0], b);
  }
  const mapped = toByteLevel('café 😀');
  assert.equal(fromByteLevel(mapped).join(','),
    [...new TextEncoder().encode('café 😀')].join(','));
  assert.match(BYTE_LEVEL_PATTERN, /\\p\{L\}/);
});

test('TP-4 the port matches Python id-for-id', () => {
  let checked = 0;
  for (const c of FIXTURE.cases) {
    assert.deepEqual(bpe.encode(c.text), c.ids,
      `encode mismatch for ${JSON.stringify(c.text)}`);
    checked += c.ids.length;
  }
  assert.equal(checked, FIXTURE.cases.reduce((n, c) => n + c.ids.length, 0));
  assert.ok(checked > 300, 'the fixture is too small to prove anything');
});

test('TP-5 every id is in range and decodes', () => {
  for (const c of FIXTURE.cases) {
    for (const id of c.ids) {
      assert.ok(Number.isInteger(id) && id >= 0 && id < bpe.vocabSize, `id ${id} out of range`);
    }
    assert.doesNotThrow(() => bpe.decode(c.ids));
  }
});

test('TP-6 decode is lossless for text without added tokens', () => {
  for (const c of FIXTURE.cases) {
    if (c.text.includes('<|')) continue;
    assert.equal(bpe.decode(c.ids), c.decoded);
  }
});

test('TP-7 framing specials are dropped on request, placeholders kept', () => {
  const ids = bpe.encode('<|sys|><|user|>hello<|asst|><|fact:contact.email|><|end|>');
  const visible = bpe.decode(ids, { skipSpecial: true });
  assert.equal(visible.includes('<|sys|>'), false);
  assert.equal(visible.includes('<|end|>'), false);
  assert.ok(visible.includes('<|fact:contact.email|>'),
    'a placeholder must survive decoding — the guard needs to see it (§7.2)');
});

test('TP-8 every placeholder the knowledge base can emit is one id', () => {
  const placeholders = SPEC.added_tokens
    .map((t) => t.content)
    .filter((c) => c.startsWith('<|fact:'));
  assert.equal(placeholders.length, META.placeholder_count,
    'the artifact must carry every placeholder the answer layer may emit');
  for (const token of placeholders) {
    assert.deepEqual(bpe.encode(token), [bpe.vocab[token]], `${token} is not one id`);
    assert.equal(bpe.decode(bpe.encode(token)), token);
  }
  // Longest-first: a longer placeholder that shares a prefix with a shorter
  // one must not be swallowed by it.
  const pair = placeholders.filter((p) => p.includes('.live|>'))[0];
  const base = placeholders.filter((p) => !p.includes('.live|>') && pair.startsWith(p.slice(0, -2)))[0];
  if (pair && base) {
    const text = `${base}${pair}`;
    assert.deepEqual(bpe.encode(text), [bpe.vocab[base], bpe.vocab[pair]]);
  }
});

test('TP-9 an incomplete artifact is rejected, loadTokenizer wraps fetch', async () => {
  const broken = { ...SPEC, model: { ...SPEC.model, vocab: { a: 0 } } };
  assert.throws(() => new ByteLevelBPE(broken), /missing the byte-level character/);
  assert.throws(() => new ByteLevelBPE({}), /no model\.vocab/);

  const fake = async () => ({ ok: true, json: async () => SPEC });
  const loaded = await loadTokenizer('tokenizer.json', { fetchImpl: fake });
  assert.equal(loaded.vocabSize, bpe.vocabSize);
  const failing = async () => ({ ok: false, status: 404 });
  await assert.rejects(() => loadTokenizer('missing.json', { fetchImpl: failing }), /404/);
});
