/* ═══════════════════════════════════════════════════════════════
   ai/engine/bpe.mjs — our own tokenizer, in the visitor's browser.

   §7.2: "Train our own BPE/Unigram ... never load a pretrained vocab."
   §2 N4: the model is ours from random init, and so is the vocabulary.
   Training happens in Python (`ai/tokenizer/train.py`); this file is the
   *encoder* — the same artifact, ported, so a text chat never needs a
   wasm runtime just to turn a question into ids.

   It is a faithful port of the HF `tokenizers` pipeline the artifact was
   built with, not an approximation:

       NFC → AddedVocabulary (literal, longest-first) → ByteLevel
       (byte→unicode char map, GPT-2 regex split) → BPE by merge rank

   The three places a port silently goes wrong are all pinned by tests
   against the Python encoder (`tests/fixtures/tokenizer_parity.json`,
   generated by `inference/encode_fixture.py`) rather than trusted:

     * `bytes_to_unicode` is *derived*, never a hardcoded table;
     * the split runs on the **raw** text and the byte map is applied to
       each piece afterwards. The other order looks equivalent on English
       and is not: a combining mark (Hindi's 'ा' is `Mn`, not `L`) breaks a
       letter run in the raw text, and if the map ran first its bytes would
       land inside runs of unrelated categories, so "आपक" and "ा" stop
       being separate pre-tokens and every Hindi id changes;
     * added tokens are matched on the raw text *before* the byte map,
       because their content is ASCII like `<|fact:contact.email|>` and
       would otherwise be shredded into byte-level pieces.

   No wasm, no worker, no network: 66 KB of JSON and this file.
   ═══════════════════════════════════════════════════════════════ */

/** GPT-2's byte→unicode map, *derived* — `bytes_to_unicode()` in the
 *  reference implementation. Printable ASCII/Latin-1 stay themselves; the
 *  other 68 bytes move into the U+0100+ range so every byte is one
 *  printable character (that is why a space becomes 'Ġ').
 *  @returns {string[]} index = byte value, value = the character. */
export function bytesToUnicode() {
  const bs = [];
  for (let b = 0x21; b <= 0x7e; b++) bs.push(b);   // '!' … '~'
  for (let b = 0xa1; b <= 0xac; b++) bs.push(b);   // '¡' … '¬'
  for (let b = 0xae; b <= 0xff; b++) bs.push(b);   // '®' … 'ÿ'
  const cs = bs.slice();
  let n = 0;
  const seen = new Uint8Array(256);
  for (const b of bs) seen[b] = 1;
  for (let b = 0; b < 256; b++) {
    if (!seen[b]) {
      bs.push(b);
      cs.push(256 + n);
      n += 1;
    }
  }
  const table = new Array(256);
  for (let i = 0; i < bs.length; i++) table[bs[i]] = String.fromCodePoint(cs[i]);
  return table;
}

const BYTE_TO_CHAR = bytesToUnicode();
const CHAR_TO_BYTE = new Map();
for (let b = 0; b < 256; b++) CHAR_TO_BYTE.set(BYTE_TO_CHAR[b], b);

/** The GPT-2 split, applied to the raw text (§ above). `\p{L}` and
 *  `\p{N}` are the Rust regex's Unicode classes, which JS supports. The
 *  `\s+(?!\S)` alternative is what makes a run of spaces split as
 *  "one space, then the rest" instead of vanishing. */
const BYTE_LEVEL_RE = /'s|'t|'re|'ve|'m|'ll|'d| ?\p{L}+| ?\p{N}+| ?[^\s\p{L}\p{N}]+|\s+(?!\S)|\s+/gu;

/** `'s|'t|…` needs the apostrophe forms only for English; the rest is the
 *  same pattern `tokenizers` compiles from the artifact's `use_regex`. */
export const BYTE_LEVEL_PATTERN = BYTE_LEVEL_RE.source;

/** The framing specials, in id order (§7.2). */
export const SPECIAL_TOKENS = ['<|sys|>', '<|ctx|>', '<|user|>', '<|asst|>', '<|end|>', '<|abstain|>'];

function utf8Bytes(text) {
  return new TextEncoder().encode(text);
}

/** Byte-mapped view of a string: one character per UTF-8 byte. */
export function toByteLevel(text) {
  const bytes = utf8Bytes(text);
  let out = '';
  for (let i = 0; i < bytes.length; i++) out += BYTE_TO_CHAR[bytes[i]];
  return out;
}

/** Inverse of `toByteLevel`, as bytes (a malformed sequence can lose a
 *  character, so this stays bytes until a whole token is assembled). */
export function fromByteLevel(mapped) {
  const out = [];
  for (const ch of mapped) {
    const b = CHAR_TO_BYTE.get(ch);
    if (b === undefined) throw new Error(`not a byte-level character: ${JSON.stringify(ch)}`);
    out.push(b);
  }
  return out;
}

/** A tokenizer, loaded from an artifact §7.2 produced.
 *
 *  The constructor takes the *parsed* `tokenizer.json` so a test can read
 *  it from disk and the browser can `fetch()` it, with identical
 *  behaviour (`loadTokenizer` is the browser path).
 */
export class ByteLevelBPE {
  constructor(spec) {
    const model = spec?.model;
    if (!model || !model.vocab) throw new Error('tokenizer artifact has no model.vocab');
    this.spec = spec;
    this.vocab = model.vocab;
    this.vocabSize = Object.keys(model.vocab).length;
    this.tokenOf = new Array(this.vocabSize);
    for (const [token, id] of Object.entries(model.vocab)) this.tokenOf[id] = token;

    // { "a b": rank }. The artifact may list merges as pairs or as
    // space-joined strings; both spellings exist in the wild.
    const merges = model.merges || [];
    this.ranks = new Map();
    for (let rank = 0; rank < merges.length; rank++) {
      const m = merges[rank];
      const key = Array.isArray(m) ? `${m[0]} ${m[1]}` : String(m);
      if (!this.ranks.has(key)) this.ranks.set(key, rank);
    }

    // Added tokens are matched literally on the raw text, longest first —
    // `<|fact:project.x.repo|>` must never be split by a shorter
    // `<|fact:project.x|>`-shaped prefix, and `<|asst|>` must beat a byte
    // decomposition of the same characters.
    const added = (spec.added_tokens || [])
      .filter((t) => t && typeof t.content === 'string' && t.content)
      .map((t) => ({ content: t.content, id: t.id, special: Boolean(t.special) }))
      .sort((a, b) => b.content.length - a.content.length);
    this.addedTokens = added;
    this.addedById = new Map(added.map((t) => [t.id, t]));
    // Byte coverage is by **alphabet, not by fallback**. The artifact was
    // trained with `initial_alphabet=ByteLevel.alphabet()`, so all 256
    // byte characters are ordinary vocabulary entries and the serialized
    // `model.byte_fallback` flag is false — the flag is unused, and
    // `meta.json`'s `byte_fallback: true` describes the property that
    // actually holds. Trusting the flag instead of the alphabet is how an
    // encoder ends up unable to spell a Devanagari character.
    this.byteFallback = model.byte_fallback === true;
    for (let b = 0; b < 256; b++) {
      if (this.vocab[BYTE_TO_CHAR[b]] === undefined) {
        throw new Error(`vocabulary is missing the byte-level character for byte ` +
          `${b} (${JSON.stringify(BYTE_TO_CHAR[b])}) — the artifact is incomplete`);
      }
    }
    this.normalizer = spec.normalizer?.type || 'NFC';
  }

  /** ids for one pre-token, by merge rank. */
  #bpePiece(piece) {
    let symbols = [...piece];
    if (symbols.length === 0) return [];
    while (symbols.length > 1) {
      let bestRank = Infinity;
      let bestAt = -1;
      for (let i = 0; i < symbols.length - 1; i++) {
        const rank = this.ranks.get(`${symbols[i]} ${symbols[i + 1]}`);
        if (rank !== undefined && rank < bestRank) {
          bestRank = rank;
          bestAt = i;
        }
      }
      if (bestAt < 0) break;
      symbols = [
        ...symbols.slice(0, bestAt),
        symbols[bestAt] + symbols[bestAt + 1],
        ...symbols.slice(bestAt + 2),
      ];
    }
    const ids = [];
    for (const sym of symbols) {
      const id = this.vocab[sym];
      if (id !== undefined) {
        ids.push(id);
      } else if (this.byteFallback) {
        // Should be unreachable (every single mapped byte is checked in the
        // constructor) but never silently drop a character.
        for (const b of fromByteLevel(sym)) ids.push(this.vocab[BYTE_TO_CHAR[b]]);
      } else {
        throw new Error(`token ${JSON.stringify(sym)} is not in the vocabulary`);
      }
    }
    return ids;
  }

  /** Raw text → pre-tokens, the way the artifact's `pre_tokenizer` splits.
   *  Exposed because it is where the Hindi bug lives (see the header). */
  preTokenize(text) {
    const normalized = String(text).normalize('NFC');
    const pieces = [];
    for (const part of this.#splitAdded(normalized)) {
      if (part.added) {
        pieces.push(part.added.content);
        continue;
      }
      BYTE_LEVEL_RE.lastIndex = 0;
      let match;
      while ((match = BYTE_LEVEL_RE.exec(part.text)) !== null) pieces.push(toByteLevel(match[0]));
    }
    return pieces;
  }

  /** Split raw text around added-token literals. */
  #splitAdded(text) {
    if (this.addedTokens.length === 0) return [{ text }];
    const parts = [];
    let rest = text;
    let guard = 0;
    while (rest.length && guard++ < 10000) {
      let at = -1;
      let found = null;
      for (const token of this.addedTokens) {
        const idx = rest.indexOf(token.content);
        if (idx < 0) continue;
        // Longest-first ordering means the first hit at the earliest
        // position is the intended one, but compare properly anyway.
        if (at < 0 || idx < at || (idx === at && token.content.length > found.content.length)) {
          at = idx;
          found = token;
        }
      }
      if (at < 0) break;
      if (at > 0) parts.push({ text: rest.slice(0, at) });
      parts.push({ added: found });
      rest = rest.slice(at + found.content.length);
    }
    if (rest.length) parts.push({ text: rest });
    return parts;
  }

  /** Text → ids. Matches the Python encoder, including specials. */
  encode(text, { addSpecialTokens = true } = {}) {
    if (text === undefined || text === null) throw new Error('encode() needs text');
    const normalized = String(text).normalize('NFC');
    const ids = [];
    for (const part of this.#splitAdded(normalized)) {
      if (part.added) {
        // `addSpecialTokens: false` still emits placeholders: they are part
        // of the *answer's meaning*, not decoration. Only the framing
        // specials can be suppressed, and callers that suppress them pass
        // text that does not contain them.
        if (!addSpecialTokens && part.added.special && !part.added.content.startsWith('<|fact:')) {
          for (const b of utf8Bytes(part.added.content)) ids.push(this.vocab[BYTE_TO_CHAR[b]]);
          continue;
        }
        ids.push(part.added.id);
        continue;
      }
      // Split the raw text, *then* byte-map each piece — the order the
      // artifact's pre_tokenizer uses (see the header).
      BYTE_LEVEL_RE.lastIndex = 0;
      let match;
      while ((match = BYTE_LEVEL_RE.exec(part.text)) !== null) {
        for (const id of this.#bpePiece(toByteLevel(match[0]))) ids.push(id);
      }
    }
    return ids;
  }

  /** ids → text. `skipSpecial` drops the framing tokens but keeps
   *  placeholders, because a decoded answer containing a placeholder is
   *  meaningful to the app layer (§7.2) and must be visible to the guard. */
  decode(ids, { skipSpecial = false } = {}) {
    const bytes = [];
    let out = '';
    const flush = () => {
      if (bytes.length === 0) return;
      out += new TextDecoder('utf-8', { fatal: false }).decode(new Uint8Array(bytes));
      bytes.length = 0;
    };
    for (const id of ids) {
      const added = this.addedById.get(id);
      if (added) {
        flush();
        if (skipSpecial && added.special && !added.content.startsWith('<|fact:')) continue;
        out += added.content;
        continue;
      }
      const token = this.tokenOf[id];
      if (token === undefined) throw new Error(`id ${id} is not in the vocabulary`);
      for (const b of fromByteLevel(token)) bytes.push(b);
    }
    flush();
    return out;
  }

  /** Round-trip a single id (used by tests and the streaming UI). */
  tokenText(id) {
    const added = this.addedById.get(id);
    if (added) return added.content;
    const token = this.tokenOf[id];
    return token === undefined ? '' : new TextDecoder().decode(new Uint8Array(fromByteLevel(token)));
  }

  get specialIds() {
    return new Set(this.addedTokens.filter((t) => t.special).map((t) => t.id));
  }
}

/** Fetch and wrap an artifact. Relative URLs keep it same-origin: the
 *  tokenizer ships inside the AI chunk, never from a CDN. */
export async function loadTokenizer(url, { fetchImpl = fetch } = {}) {
  const response = await fetchImpl(url);
  if (!response.ok) throw new Error(`tokenizer fetch failed: ${response.status} ${url}`);
  return ByteLevelBPE.fromJSON(await response.json());
}

/** Parse an artifact already in memory (a bundled `import` or a test). */
ByteLevelBPE.fromJSON = function fromJSON(spec) {
  return new ByteLevelBPE(spec);
};
