"""inference/encode_fixture.py — the JS tokenizer port's reference.

`ai/engine/bpe.mjs` re-implements the encoder that `tokenizers` builds
from our artifact. A port that is "probably right" is exactly the kind of
thing that quietly degrades Hindi by 10 points and is never noticed, so the
port is checked against the original instead: this writes
`tests/fixtures/tokenizer_parity.json` from the *Python* tokenizer, and
`tests/tokenizer-parity.test.mjs` asserts the JS encoder returns exactly
those ids.

    PYTHONIOENCODING=utf-8 python inference/encode_fixture.py

The fixture is small, committed, and regenerated only when the artifact
changes (the artifact's `meta.json` records the hash the fixture was built
against; the test reads it so a stale fixture fails loudly).
"""

from __future__ import annotations

import argparse
import hashlib
import io
import json
import sys
from pathlib import Path

if __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_ARTIFACT = ROOT / "ai/tokenizer/artifacts/seed-1k"
DEFAULT_OUT = ROOT / "tests/fixtures/tokenizer_parity.json"

# Deliberately awkward: the four languages we ship, NFC-relevant accents and
# Devanagari, JSON-ish punctuation, a URL, an email, a placeholder that must
# survive as one id, a byte that has no single-character form (emoji), an
# empty string, and a lone space.
CASES = [
    "",
    " ",
    "hello",
    "Hello, Aashish here.",
    "What is Aashish's email address?",
    "  leading and trailing  ",
    "Aashish built a Smart Grocery List Generator with React and Node.js",
    "React, Node.js, Python, TypeScript — REST APIs and PostgreSQL",
    "contact me at aashish@example.com or https://github.com/aashish",
    "<|fact:contact.email|>",
    "<|sys|><|ctx|><|user|>tell me about the projects<|asst|>",
    "<|abstain|>",
    "आपका नाम क्या है?",
    "आशीष के प्रोजेक्ट्स के बारे में बताइए।",
    "mera naam Aashish hai, main ek full-stack developer hoon",
    "Hinglish: kya aapko React aata hai? haan, 3 saal ka experience hai",
    "café naïve résumé — 5 × 3 ≥ 15",
    "emoji 😀 and a tab\there",
    "line one\nline two\r\nline three",
    "const x = (a, b) => a + b; // comment",
    "हिंदी और English मिला हुआ 123",
]


def main(argv: list[str] | None = None) -> int:
    # Windows consoles default to cp1252; our summary line uses an em dash.
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")

    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--artifact", default=str(DEFAULT_ARTIFACT))
    ap.add_argument("--out", default=str(DEFAULT_OUT))
    args = ap.parse_args(argv)

    from tokenizers import Tokenizer  # noqa: E402

    artifact = Path(args.artifact)
    tok_file = artifact / "tokenizer.json"
    raw = tok_file.read_bytes()
    tok = Tokenizer.from_file(str(tok_file))

    cases = []
    for text in CASES:
        ids = tok.encode(text).ids
        cases.append({
            "text": text,
            "ids": ids,
            "decoded": tok.decode(ids),
        })

    meta_path = artifact / "meta.json"
    meta = json.loads(meta_path.read_text(encoding="utf-8")) if meta_path.exists() else {}
    fixture = {
        "artifact": str(artifact.relative_to(ROOT)).replace("\\", "/"),
        "tokenizer_version": meta.get("tokenizer_version"),
        "vocab_size": tok.get_vocab_size(),
        "artifact_sha256": hashlib.sha256(raw).hexdigest(),
        "note": ("Generated by inference/encode_fixture.py from the Python "
                 "tokenizer. tests/tokenizer-parity.test.mjs requires "
                 "ai/engine/bpe.mjs to return exactly these ids."),
        "cases": cases,
    }

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(fixture, ensure_ascii=False, indent=2) + "\n",
                   encoding="utf-8")
    total = sum(len(c["ids"]) for c in cases)
    print(f"wrote {out.relative_to(ROOT)} — {len(cases)} cases, {total} ids, "
          f"vocab {fixture['vocab_size']}, artifact {fixture['artifact_sha256'][:12]}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
