"""inference/export_prompt_contract.py — the §7.4 frame, shared with JavaScript.

    python inference/export_prompt_contract.py          # write it
    python inference/export_prompt_contract.py --check   # fail if it drifted

`ai/data/instruction.py` owns the frame the model is trained on:
the two rule strings, the six special tokens, the joined-with-a-space
layout. `ai/engine/prompt.mjs` has to rebuild that exact string in the
browser, and two copies of a prompt format is how a model ends up "broken"
after a deploy that changed nothing about the model.

So the constants are exported once into `ai/engine/prompt_contract.json`,
which the JavaScript imports. `--check` is the drift test: it re-renders
and compares, so editing `instruction.py` without re-running this fails
`npm run test:py` instead of quietly changing what the model sees.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

if __package__ in (None, ""):
    sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

from ai.data import instruction  # noqa: E402
from ai.tokenizer import spec  # noqa: E402

ROOT = Path(__file__).resolve().parents[1]
DEFAULT_OUT = ROOT / "ai/engine/prompt_contract.json"

# The order of the parts in `format_example`, spelled out so a change to the
# layout is a change to this list and not only to a function's body.
LAYOUT = ["sys", "rules", "ctx", "context", "turns"]
TURN = ["user", "text", "asst", "answer", "end"]


def render() -> dict:
    frames = {
        "sys": instruction.SYS,
        "ctx": instruction.CTX,
        "user": instruction.USER,
        "asst": instruction.ASST,
        "end": instruction.END,
        "abstain": instruction.ABSTAIN,
    }
    assert tuple(frames[k] for k in ("sys", "ctx", "user", "asst", "end", "abstain")) \
        == spec.SPECIAL_TOKENS, "the frames must be the §7.2 specials in order"
    return {
        "version": "7.4",
        "source": "ai/data/instruction.py",
        "joining": " ",
        "layout": LAYOUT,
        "turn": TURN,
        "frames": frames,
        "rules": {"first": instruction.RULES["first"],
                  "third": instruction.RULES["third"]},
        "personas": list(instruction.PERSONAS),
        "metaAnswer": instruction.META_ANSWER,
        "safeReply": instruction.SAFE_REPLY,
        "note": ("Generated by inference/export_prompt_contract.py. "
                 "The runtime prompt must be built from these strings; "
                 "tests/py/test_prompt_contract.py fails if this file is stale."),
    }


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", default=str(DEFAULT_OUT))
    ap.add_argument("--check", action="store_true",
                    help="exit 1 when the file on disk differs from a fresh render")
    args = ap.parse_args(argv)

    contract = render()
    text = json.dumps(contract, ensure_ascii=False, indent=2) + "\n"
    out = Path(args.out)

    if args.check:
        current = out.read_text(encoding="utf-8") if out.exists() else ""
        if current != text:
            print(f"STALE: {out.relative_to(ROOT)} does not match ai/data/instruction.py — "
                  f"rerun `python inference/export_prompt_contract.py`", file=sys.stderr)
            return 1
        print(f"prompt contract is current ({out.relative_to(ROOT)})")
        return 0

    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(text, encoding="utf-8")
    print(f"wrote {out.relative_to(ROOT)} — "
          f"{len(contract['frames'])} frames, {len(contract['rules'])} rule sets")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
